### ISSUE TITLE
URGENT: GoogleMyBusiness API: v4.9 removed completely, although documentation still supports some endpoints that haven't been replaced yet

### ISSUE THREAD

**Issue by nekromoff** [googleapis/google-api-php-client-services#580] opened 2022-01-13 10:36 UTC
See:
https://developers.google.com/my-business/reference/rest/v4/accounts.locations/reportInsights

Also:
https://developers.google.com/my-business/reference/rest/v4/accounts.locations.reviews

And a couple of other endpoints are missing.

These endpoints have not been replaced by the new v1 API so far, but they have been completely removed from the PHP code base, so the service usage is completely hindered.

**Comment by nekromoff** [comment] 2022-01-14 10:01
Probably it wasn't part of this library before either, but this should be included in the services until the API is completely available under new v1:
https://developers.google.com/my-business/samples/google-api-services-mybusiness-v4p9-php-rev-20210224-1.zip

**Comment by nekromoff** [comment] 2022-01-14 10:54
Actually, v4.9 (linked) does not work either, weird errors such as 
```
Path locations/XXXXXXXXXXXXXXXXXXXXX does not match any known templates
```
given. Path is correct per API docs here:
https://developers.google.com/my-business/reference/rest/v4/accounts.locations/reportInsights

**Comment by nekromoff** [comment] 2022-01-14 10:55
It seems to me that former v4.9 API is completely broken without existing replacement opposite to what documentation says.

**Comment by pavlinagargova** [comment] 2022-03-01 14:12
Are you sure about that? I'm currently using both endpoints you mentioned above and they are working as expected.

**Comment by nekromoff** [comment] 2022-03-01 14:58
See when this was posted. They have fixed the library since.

However 4.9 endpoints have been completely removed without replacement. That is still outstanding issue. Try to get reviews and insights. Good luck.

**Comment by nekromoff** [comment] 2022-03-01 15:05
How are you getting them, if there are no functions to call them?

[image: image.png]
Post your code to demonstrate, but I doubt you are using this library in
its current version as the v4.9 endpoints have been removed. All endpoints
listed above are v1.

**Comment by pavlinagargova** [comment] 2022-03-01 15:12
My bad, version I'm using is 4.8, but I can see here https://developers.google.com/my-business/samples/previousVersions#v49 that listAccountsLocationsReviews, updateReply, reportInsights etc. are present.

**Comment by nekromoff** [comment] 2022-03-01 15:16
That's correct. But the current version of this library does not support
these endpoints although they have not been deprecated.
And that is the point of this bug report.

**Comment by nekromoff** [comment] 2022-03-01 15:18
I have added the existing v4.9 endpoints as a helper to my tool. I am posting the code, maybe it helps someone.
```
class GMBHelper
{

    /** v4.9 working 02/2022 **/
    public static function listReviews($client, $params, $account, $location)
    {
        $response = $client->authorize()->get('https://mybusiness.googleapis.com/v4/' . $account . '/' . $location . '/reviews', ['query' => $params]);
        return json_decode((string) $response->getBody(), false);
    }

    /** v4.9 working 02/2022 **/
    public static function reportInsights($client, $params, $account)
    {
        try {
            $response = $client->authorize()->post('https://mybusiness.googleapis.com/v4/' . $account . '/locations:reportInsights', [
                \GuzzleHttp\RequestOptions::JSON => $params,
            ]);
        } catch (\GuzzleHttp\Exception\RequestException $ex) {
            return $ex->getResponse()->getBody()->getContents();
        }
        return json_decode((string) $response->getBody(), false);
    }

    /** v1 replacement for non-working "readMask" required error, but this endpoint does not require readMask **/
    public static function listQuestions($client, $location, $params)
    {
        try {
            $response = $client->authorize()->get('https://mybusinessqanda.googleapis.com/v1/' . $location . '/questions', ['query' => $params]);
        } catch (\GuzzleHttp\Exception\RequestException $ex) {
            return $ex->getResponse()->getBody()->getContents();
        }
        return json_decode((string) $response->getBody(), false);
    }

}
```

**Comment by bshaffer** [comment] 2022-03-16 19:42
The page you linked to contains the previous version. This library is generated entirely from endpoints published by the API teams themselves (in this case, the [mybusinessQA discovery doc](https://mybusinessqanda.googleapis.com/$discovery/rest?version=v1). So if those endpoints don't exist in the current version, it was a decision by the current API team to not support those API endpoints in the current version. Unfortunately I cannot speak to why this decision was made, but this is Working As Designed.

**Comment by nekromoff** [comment] 2022-03-16 19:52
It seems that you are not well acquainted with the MyBusiness endpoints.
Indeed, it is a previous version, but: these endpoints have not been
deprecated based on the MyBusiness API changelog. In fact, they haven't
been replaced with v1 and that's the reason. Until that happens, the only
way is to use these hanging v4.9 endpoints.

**Comment by adrianlaraperez88** [comment] 2022-11-19 09:06
Hi Google Api Team, any update in this task i have issue with Insights and other endpoints

**Comment by bshaffer** [comment] 2022-11-21 15:27
This client library only publishes the most recent version of any of our APIs as defined by that API's [Discovery JSON](https://discovery.googleapis.com/discovery/v1/apis). MyBusiness is referencing a discovery document at https://mybusiness.googleapis.com/$discovery/rest?version=v4 in their [API reference documentation](https://developers.google.com/my-business/reference/rest), but unfortunately that URL is unreachable.

I've filed an internal issue with their team to try and track down what happened. In the meantime, if there's a previous version of this library which supports MyBusiness, you could

**Comment by Eldair** [comment] 2022-11-22 15:52
Old endpoints still work and client library was never in this repo (there was a direct download link for php file 😆).

**Comment by adrianlaraperez88** [comment] 2022-12-14 04:18
@Eldair Any update on this task, I continue with the issue at times to try downloading the location Insights Report(accounts.locations.reportInsights)

**Comment by Eldair** [comment] 2022-12-14 10:19
@adrianlaraperez88 I'm not a maintainer here, I just added my opinion on this :/
regarding accounts.locations.reportInsights (which still works) there is now a replacement endpoint (locations.getDailyMetricsTimeSeries), but it is very lacking (only one metric per request and a bunch of metrics are removed)

**Comment by bshaffer** [comment] 2022-12-15 00:55
> Old endpoints still work and client library was never in this repo (there was a direct download link for php file 😆).

Well, that explains a lot. No wonder we're having so many issues. 

> For anyone interested, this is the My Business PHP classes

It would be possible to host these somewhere separate (such as `bshaffer/google-mybusiness-client`) so that those who need it can use it. For now, anyone coming here can download and include the files in their code using @Eldair's link above.

**Comment by bshaffer** [comment] 2022-12-16 00:20
I've added a package `bshaffer/apiclient-mybusiness-service`, which is just the previous package, but added back to packagist so you can pull it down and use it. You can see the repo here: https://github.com/bshaffer/google-mybusiness-php-client

Use it as follows:

```
composer require bshaffer/apiclient-mybusiness-service
```

And then in your code:

```php
require 'vendor/autoload.php';

$client = new Google\Client;
$mybusiness = new Google_Service_MyBusiness($client);
$response = $mybusiness->accounts_locations_reviews->listAccountsLocationsReviews('accounts/foo/locations/bar');
```

I'm closing this because I think there is no better solution, as the discovery document (which is used by this repo) has been removed.

**Closed by bshaffer** 2022-12-16 00:20 UTC
Labels: status: investigating, triage me, :rotating_light:
