### ISSUE TITLE
Google_Service_Drive_DriveFile extends Google_Collection whereas Google_Service_Drive_Drive extends Google_Model

### ISSUE THREAD

**Issue by marekdedic** [googleapis/google-api-php-client-services#221] opened 2020-10-09 10:01 UTC
Hi,
I noticed a difference between 2 classes which perform a very similar function: `Google_Service_Drive_DriveFile` and `Google_Service_Drive_Drive`. One of them extends `Google_Model`, whereas the other extends `Google_Collection` (which in turn extends `Google_Model`).

How this impacts the actual user: `Google_Collection` implements `Iterator`, `Google_Model` implements only `ArrayAccess`. So, in actual code:

```php
$params = array(
	'q'                         => 'trashed = false',
	'fields'                    => 'files(name)',
);
$response = self::get_drive_client()->files->listFiles( $params );
foreach ( $response->getFiles() as $file ) { // <-- This works
	echo( $file->getName() );
}
```

```php
$params = array(
	'fields'    => 'drives(name)',
);
$response = self::get_drive_client()->drives->listDrives( $params );
foreach ( $response->getDrives() as $drive ) { // <-- This complains about Google_Service_Drive_Drive not implementing Traversable
	echo( $drive->getName() ),
}
```

So, almost identical code, different result... Could this be changed so that `Google_Service_Drive_Drive` extends `Google_Collection` as well?

#### Environment details

  - OS: Debian testing
  - PHP version: 7.4.10
  - Package name and version: `google/apiclient v2.7.2` and `google/apiclient-services v0.146`

**Comment by danoscarmike** [comment] 2020-10-16 16:29
@bshaffer @dwsupplee can you take a look?

**Comment by bshaffer** [comment] 2020-11-23 15:23
The reason `Google_Service_Drive_DriveFile` extends `Google_Collection` is that you can iterate over "spaces". There's no reason for `Google_Service_Drive_Drive` to implement `Google_Collection`, as `Google_Service_Drive_DriveList::getDrives` should return an array of `Google_Service_Drive_Drive`.

I believe the issue you're reporting is a duplicate of https://github.com/googleapis/google-api-php-client-services/issues/123

**Comment by marekdedic** [comment] 2020-11-23 16:33
So, if I understand you correctly, you are saying that the issues is that `Google_Service_Drive_DriveList::getDrives` has an incorrect type annotation (it says it returns `Google_Service_Drive_Drive` but it should actually be `Google_Service_Drive_Drive[]`). Is that correct?

Thanks

**Closed** 2020-11-30 19:12 UTC
Labels: type: feature request
