### ISSUE TITLE
MyBusinessBusinessInformation locations.getAttributes method wrong path

### ISSUE THREAD

**Issue by Kateihen** [googleapis/google-api-php-client-services#964] opened 2022-04-28 07:35 UTC
In `MyBusinessBusinessInformation` class `locations.getAttributes` method has wrong path.
According to the API documentation, the path must be the following:
![2](https://user-images.githubusercontent.com/46999482/165700353-abd40465-7348-429e-be34-d8307e4795b0.png)

But in the code the path is the following:
![1](https://user-images.githubusercontent.com/46999482/165700421-8e5e383a-b564-4761-b00d-484c9f73975a.png)

The path in `getAttributes` is the same as in `get` method which is obviously wrong.

Due to this, when I make request to `getAttributes` endpoint I receive the following error:
```
​ {
      "error": {
        "code": 400,
        "message": "Request contains an invalid argument.",
        "errors": [
          {
            "message": "Request contains an invalid argument.",
            "domain": "global",
            "reason": "badRequest"
          }
        ],
        "status": "INVALID_ARGUMENT",
        "details": [
          {
            "@type": "type.googleapis.com/google.rpc.BadRequest",
            "fieldViolations": [
              {
                "field": "read_mask",
                "description": "Field is required"
              }
            ]
          }
        ]
      }
    }
```
even though `read_mask` is not required for this endpoint according to the documentation.

But when I provide `read_mask` I receive the next exception: 
'Google/Exception with message '(getAttributes) unknown parameter: 'read_mask''.

And when I've manually fixed the path in MyBusinessBusinessInformation everything works as intended.

**Comment by bshaffer** [comment] 2022-05-09 21:28
This seems to be a duplicate of #956 

These classes are autogenerated, so this change would be overwritten by the next release. Furthermore, if this is truly an error, it would be an error in the discovery API itself, and so the fix would need to go there.

The [discovery doc](https://mybusinessqanda.googleapis.com/$discovery/rest?version=v1) shows the path we have in the library here as the path for listing questions. There's nothing we can do here unless that changes. I would suggest [contacting the API team](https://support.google.com/business/contact/api_default) if you think this is an error. 

The maintainers of this repo only make sure the generated clients match the API's discovery doc, and do not support any specific API usage questions (there are over 200 APIs, so it would be impossible for us to do that)

**Closed by bshaffer** 2022-05-09 21:28 UTC
Labels: triage me, :rotating_light:

**Comment by bshaffer** [comment] 2022-05-09 22:00
So, looking at the discovery doc, the parent parameter should contain "/attributes" in the path:

```json
{
"list": {
    "parameters": {
        "name": {
            "description": "Required. Google identifier for this location in the form of `locations/{location_id}/attributes`.",
            "location": "path",
            "pattern": "^locations/[^/]+/attributes$",
            "required": true,
            "type": "string"
        },
    }
}
```

So the correct usage should be:

```php
$myBusinessInformationService = new MyBusinessBusinessInformation($client);
$attributes = $myBusinessInformationService->locations->getAttributes('locations/LOCATION_NAME/attributes');
```

I agree this is not very intuitive, but I believe this is how the API is designed.
