### ISSUE TITLE
ConferenceData->getEntryPoints() returns array, but stated Google_Service_Calendar_EntryPoint in annotations

### ISSUE THREAD

**Issue by Deifinger** [googleapis/google-api-php-client-services#209] opened 2020-07-16 12:39 UTC
#### Environment details

  - OS: Ubuntu 20.04 LTS
  - PHP version: 7.2
  - Package name and version: "google/apiclient": "^2.0"

#### Steps to reproduce

  1. Insert new event with google meet conference:
```
       $calendarEvent = $service->events->insert(self::DEFAULT_CALENDAR_ID, $event, [
            'sendUpdates' => 'all',
            'conferenceDataVersion' => 1,
        ]);
```
  2. Take Google_Service_Calendar_Event as a result of previous step and get entry points:
```
$calendarEvent->getConferenceData()->getEntryPoints()
```
3. You will get array of 'Google_Service_Calendar_EntryPoint':
```
array:3 [
  0 => Google_Service_Calendar_EntryPoint {#1580
    #collection_key: "entryPointFeatures"
    +accessCode: null
    +entryPointFeatures: null
    +entryPointType: "video"
    +label: "meet.google.com/dez-uoxx-axo"
    +meetingCode: null
    +passcode: null
    +password: null
    +pin: null
    +regionCode: null
    +uri: "https://meet.google.com/dez-uoxx-axo"
    #internal_gapi_mappings: []
    #modelData: []
    #processed: []
  }
  1 => Google_Service_Calendar_EntryPoint {#1581
    #collection_key: "entryPointFeatures"
    +accessCode: null
    +entryPointFeatures: null
    +entryPointType: "more"
    +label: null
    +meetingCode: null
    +passcode: null
    +password: null
    +pin: "6050977172537"
    +regionCode: null
    +uri: "https://tel.meet/dez-uoxx-axo?pin=6050977172537"
    #internal_gapi_mappings: []
    #modelData: []
    #processed: []
  }
  2 => Google_Service_Calendar_EntryPoint {#1582
    #collection_key: "entryPointFeatures"
    +accessCode: null
    +entryPointFeatures: null
    +entryPointType: "phone"
    +label: "+44 20 3957 3258"
    +meetingCode: null
    +passcode: null
    +password: null
    +pin: "931969790"
    +regionCode: "GB"
    +uri: "tel:+44-20-3957-3258"
    #internal_gapi_mappings: []
    #modelData: []
    #processed: []
  }
]
```

#### Description

**Actual:** Open src/Google/Service/Calendar/ConferenceData.php class, you will see Google_Service_Calendar_EntryPoint in annotations for getEntryPoints() method
```
/**
   * @return Google_Service_Calendar_EntryPoint
   */
  public function getEntryPoints()
  {
    return $this->entryPoints;
  }
```

**Expected** For getEntryPoints() method in annotations should be set array of Google_Service_Calendar_EntryPoint classes:
```
/**
   * @return Google_Service_Calendar_EntryPoint[]
   */
  public function getEntryPoints()
  {
    return $this->entryPoints;
  }
```

**Comment by jdpedrie** [comment] 2020-07-16 13:22
Duplicate of #172.

@Deifinger Thanks for the report. This is a known issue and we're working to resolve it in updates to the code generator.

**Closed by jdpedrie** 2020-07-16 13:22 UTC
