### ISSUE TITLE
Google_Service_Directory_Resource_Channels->stop() uses wrong URI

### ISSUE THREAD

**Issue by kiliansch** [googleapis/google-api-php-client-services#102] opened 2018-01-29 14:38 UTC
When trying to call the mentioned endpoint, the URL being called is the following: `https://www.googleapis.com/admin/directory/v1//admin/directory_v1/channels/stop` instead of `https://www.googleapis.com/admin/directory_v1/channels/stop`.

**Comment by mattwhisenhunt** [comment] 2018-02-22 17:33
Duplicate of #44

**Comment by dwsupplee** [comment] 2019-06-14 23:55
Closing in favor of #44

**Closed by dwsupplee** 2019-06-14 23:55 UTC
Labels: :rotating_light:, priority: p2, status: duplicate, type: bug
