### ISSUE TITLE
\Google\Service\Calendar\Event::getDescription() returns NULL instead of ""

### ISSUE THREAD

**Issue by marios88** [googleapis/google-api-php-client-services#2682] opened 2023-04-19 13:37 UTC
#### Environment details

  - OS: Linux
  - PHP version: 8.1.17
  - Package name and version: google/apiclient:2.13.2

#### Steps to reproduce

  1. Get any event from calendar api that has an empty description

#### Code example

```php
/** @var \Google_Service_Calendar_Event $event */
var_dump($event->getDescription() === null);
```

https://github.com/googleapis/google-api-php-client-services/blob/bf6dd4985eb448d19b7ce2a4833264bacf139da9/src/Calendar/Event.php#L50

https://github.com/googleapis/google-api-php-client-services/blob/bf6dd4985eb448d19b7ce2a4833264bacf139da9/src/Calendar/Event.php#L280

**Comment by bshaffer** [comment] 2023-06-28 22:11
Hello. This is probably working as designed. Do you think it should return string because the parameter type in phpdoc is `string` instead of `string|null`? Because this may be an issue. But I believe if the API was returning an empty string, this method would also.

**Comment by yash30201** [comment] 2023-07-27 10:19
Closing as this seems answered. Please feel free to reopen if your still have any query.

**Closed by yash30201** 2023-07-27 10:19 UTC
Labels: type: question
