### ISSUE TITLE
Incorrectly documented return type for Google_Service_ServiceControl_CheckResponse::getCheckErrors()

### ISSUE THREAD

**Issue by bigdawggi** [googleapis/google-api-php-client-services#187] opened 2019-11-21 02:00 UTC
The docblock's `@return` type for `Google_Service_ServiceControl_CheckResponse::getCheckErrors()` is incorrect.  The method returns a PHP `array` and not `Google_Service_ServiceControl_CheckError` as documented.  

#### Suggested action

Correct the docblock to be "`@return array of Google_Service_ServiceControl_CheckError objects`"

#### Environment details

  - OS: macOS Mojave (not important)
  - PHP version: 7.2.7 (not important)
  - Package name and version: googleapis/google-api-php-client-services master

#### Steps to reproduce

  1. Using a valid `Google_Service_ServiceControl` make a `check()` request with a `Google_Service_ServiceControl_CheckRequest` that's invalid - an easy way to do it is to have an invalid project number filled in with the `Google_Service_ServiceControl_Operation`
  2. With the results of the `check()` method (which is a `Google_Service_ServiceControl_CheckRequest`), call its `getCheckErrors()` method.
  3. Examine the results of the `getCheckErrors()` method, and notice it's an `array` instead of what the method's docblock specifies with a return type of `Google_Service_ServiceControl_CheckError`

#### Code example

```php
use Google_Client as Client;
use Google_Service_ServiceControl as ServiceControl;
use Google_Service_ServiceControl_CheckRequest as CheckRequest;
use Google_Service_ServiceControl_Operation as Operation;

$operation = new Operation([
    'operationId'     => 'some-unique-id-here',
    'operationName'   => 'some-operation-name-here',
    'consumerId'      => 'some-consumer-id-here',
    'startTime'       => '2019-06-18T17:47:00+00:00',
    'endTime'         => '2019-06-18T17:48:00+00:00',
    'metricValueSets' => [
        [
            'metricName'   => 'some-metric-name-here',
            'metricValues' => [
                ['int64Value' => 1234]
            ],
        ],
    ],
]);

$client = new Client();
$client->useApplicationDefaultCredentials();
$client->addScope('https://www.googleapis.com/auth/cloud-platform');

$serviceControl = new ServiceControl($client);

$checkResponse = $serviceControl->services->check(
    'some-service-name-here',
    new CheckRequest(['operation' => $operation])
);
$errors = $checkResponse->getCheckErrors();
echo gettype($errors); // yields "array", not "Google_Service_ServiceControl_CheckError"
```

**Comment by erlangp** [comment] 2020-06-11 05:08
@jdpedrie ask sir

in the docs says:
https://github.com/googleapis/google-api-php-client-services/blob/f5dbae77c5c399020aef90977b152596916ec947/src/Google/Service/AndroidPublisher/TrackRelease.php#L62

what variable type that should i pass? array? or just an object?

**Comment by erlangp** [comment] 2020-06-11 05:13
https://github.com/googleapis/google-api-php-client-services/blob/f5dbae77c5c399020aef90977b152596916ec947/src/Google/Service/AndroidPublisher/Track.php#L26

too

**Comment by jdpedrie** [comment] 2020-06-11 12:57
Which API method are you calling?

**Comment by erlangp** [comment] 2020-06-11 13:31
i'am calling method `setReleaseNotes()` from object of Google_Service_AndroidPublisher_TrackRelease

**Comment by erlangp** [comment] 2020-06-11 13:33
also calling `setReleases` from an object of `Google_Service_AndroidPublisher_Track`

**Comment by jdpedrie** [comment] 2020-06-11 15:45
The type should be `Google_Service_AndroidPublisher_LocalizedText[]`, i.e. an array filled with instances of `Google_Service_AndroidPublisher_LocalizedText`.

**Comment by erlangp** [comment] 2020-06-11 16:11
thanks sir, so i need to pass array to setReleases too :+1:

**Comment by jdpedrie** [comment] 2020-07-16 13:22
Duplicate of #172.

**Closed by jdpedrie** 2020-07-16 13:22 UTC
Labels: priority: p2, type: feature request
